import Foundation
import ImageIO

struct ClipboardHistoryEntry: Codable, Identifiable, Equatable, Sendable {
    enum Content: Codable, Equatable, Sendable {
        case text(String)
        case url(String)
        case image(Data, type: String)

        var byteCount: Int {
            switch self {
            case .text(let value), .url(let value): value.utf8.count
            case .image(let data, _): data.count
            }
        }

        var searchText: String {
            switch self {
            case .text(let value), .url(let value): value
            case .image: ""
            }
        }

        var isValid: Bool {
            switch self {
            case .text(let value):
                return !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                    && byteCount <= ClipboardHistoryPolicy.maximumTextBytes
            case .url(let value):
                return byteCount <= ClipboardHistoryPolicy.maximumTextBytes
                    && URL(string: value).map {
                        ["http", "https"].contains($0.scheme?.lowercased() ?? "") && !($0.host ?? "").isEmpty
                    } == true
            case .image(let data, let type):
                guard !data.isEmpty, data.count <= ClipboardHistoryPolicy.maximumImageBytes,
                      ["public.png", "public.tiff"].contains(type),
                      let source = CGImageSourceCreateWithData(data as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
                      CGImageSourceGetCount(source) == 1,
                      CGImageSourceGetType(source) as String? == type,
                      let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
                      let width = properties[kCGImagePropertyPixelWidth] as? Int,
                      let height = properties[kCGImagePropertyPixelHeight] as? Int else { return false }
                return width > 0 && height > 0 && width <= 16_384 && height <= 16_384
                    && width * height <= 32_000_000
            }
        }
    }

    let id: UUID
    var copiedAt: Date
    let content: Content
    var isFavorite: Bool

    init(id: UUID = UUID(), copiedAt: Date = Date(), content: Content, isFavorite: Bool = false) {
        self.id = id
        self.copiedAt = copiedAt
        self.content = content
        self.isFavorite = isFavorite
    }

    private enum CodingKeys: String, CodingKey { case id, copiedAt, content, isFavorite }
    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        id = try values.decode(UUID.self, forKey: .id)
        copiedAt = try values.decode(Date.self, forKey: .copiedAt)
        content = try values.decode(Content.self, forKey: .content)
        isFavorite = try values.decodeIfPresent(Bool.self, forKey: .isFavorite) ?? false
    }
}
enum ClipboardContentFilter: String, CaseIterable, Identifiable {
    case all, favorites, text, links, images
    var id: Self { self }
    var title: String {
        switch self {
        case .all: String(localized: "All")
        case .favorites: String(localized: "Favorites")
        case .text: String(localized: "Text")
        case .links: String(localized: "Links")
        case .images: String(localized: "Images")
        }
    }
    func includes(_ entry: ClipboardHistoryEntry) -> Bool {
        switch (self, entry.content) {
        case (.all, _), (.text, .text), (.links, .url), (.images, .image): true
        case (.favorites, _): entry.isFavorite
        default: false
        }
    }
}

enum ClipboardHistoryPolicy {
    static let maximumTextBytes = 256 * 1_024
    static let maximumImageBytes = 5 * 1_024 * 1_024
    static let maximumTotalBytes = 20 * 1_024 * 1_024
    // JSON escaping and base64 can be larger than the decoded content budget.
    static let maximumEncodedBytes = 64 * 1_024 * 1_024
    static let maximumEntries = 30
    static let supportedEntryLimits = [30, 100, 300]
    static let maximumFavorites = 30
    static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "PasswordPboardType",
    ]

    static func permits(types: Set<String>, sourceIsIgnored: Bool) -> Bool {
        !sourceIsIgnored && types.isDisjoint(with: sensitiveTypes) && !types.contains("public.file-url")
    }

    static func trimmed(_ entries: [ClipboardHistoryEntry], now: Date, retentionDays: Int,
                        entryLimit: Int = maximumEntries) -> [ClipboardHistoryEntry] {
        let cutoff = now.addingTimeInterval(-Double(max(1, retentionDays)) * 86_400)
        var result: [ClipboardHistoryEntry] = []
        var bytes = 0
        var ids = Set<UUID>()
        var favorites = 0
        var ordinary = 0
        let limit = supportedEntryLimits.contains(entryLimit) ? entryLimit : maximumEntries
        for entry in entries.sorted(by: {
            if $0.isFavorite != $1.isFavorite { return $0.isFavorite }
            return $0.copiedAt > $1.copiedAt
        }) {
            guard entry.content.isValid, entry.isFavorite || entry.copiedAt > cutoff,
                  ids.insert(entry.id).inserted,
                  !result.contains(where: { $0.content == entry.content }) else { continue }
            guard (entry.isFavorite ? favorites < maximumFavorites : ordinary < limit),
                  bytes + entry.content.byteCount <= maximumTotalBytes else { continue }
            result.append(entry)
            bytes += entry.content.byteCount
            if entry.isFavorite { favorites += 1 } else { ordinary += 1 }
        }
        return result
    }

    static func inserting(_ content: ClipboardHistoryEntry.Content, into entries: [ClipboardHistoryEntry],
                          now: Date, retentionDays: Int, entryLimit: Int = maximumEntries) -> [ClipboardHistoryEntry] {
        guard content.isValid else { return entries }
        let existing = entries.first(where: { $0.content == content })
        return trimmed([ClipboardHistoryEntry(id: existing?.id ?? UUID(), copiedAt: now,
                                             content: content, isFavorite: existing?.isFavorite ?? false)]
                       + entries.filter { $0.content != content }, now: now, retentionDays: retentionDays,
                       entryLimit: entryLimit)
    }
}
