import Foundation
import ImageIO

struct ClipboardHistoryEntry: Codable, Identifiable, Equatable, Sendable {
    enum Content: Codable, Equatable, Sendable {
        case text(String)
        case url(String)
        case image(Data, type: String)

        var byteCount: Int {
            switch self {
            case .text(let value), .url(let value): value.utf8.count
            case .image(let data, _): data.count
            }
        }

        var searchText: String {
            switch self {
            case .text(let value), .url(let value): value
            case .image: ""
            }
        }

        var isValid: Bool {
            switch self {
            case .text(let value):
                return !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                    && byteCount <= ClipboardHistoryPolicy.maximumTextBytes
            case .url(let value):
                return byteCount <= ClipboardHistoryPolicy.maximumTextBytes
                    && URL(string: value).map {
                        ["http", "https"].contains($0.scheme?.lowercased() ?? "") && !($0.host ?? "").isEmpty
                    } == true
            case .image(let data, let type):
                guard !data.isEmpty, data.count <= ClipboardHistoryPolicy.maximumImageBytes,
                      ["public.png", "public.tiff"].contains(type),
                      let source = CGImageSourceCreateWithData(data as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
                      CGImageSourceGetCount(source) == 1,
                      CGImageSourceGetType(source) as String? == type,
                      let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
                      let width = properties[kCGImagePropertyPixelWidth] as? Int,
                      let height = properties[kCGImagePropertyPixelHeight] as? Int else { return false }
                return width > 0 && height > 0 && width <= 16_384 && height <= 16_384
                    && width * height <= 32_000_000
            }
        }
    }

    let id: UUID
    var copiedAt: Date
    let content: Content

    init(id: UUID = UUID(), copiedAt: Date = Date(), content: Content) {
        self.id = id
        self.copiedAt = copiedAt
        self.content = content
    }
}

enum ClipboardHistoryPolicy {
    static let maximumTextBytes = 256 * 1_024
    static let maximumImageBytes = 5 * 1_024 * 1_024
    static let maximumTotalBytes = 20 * 1_024 * 1_024
    // JSON escaping and base64 can be larger than the decoded content budget.
    static let maximumEncodedBytes = 64 * 1_024 * 1_024
    static let maximumEntries = 30
    static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "PasswordPboardType",
    ]

    static func permits(types: Set<String>, sourceIsIgnored: Bool) -> Bool {
        !sourceIsIgnored && types.isDisjoint(with: sensitiveTypes) && !types.contains("public.file-url")
    }

    static func trimmed(_ entries: [ClipboardHistoryEntry], now: Date, retentionDays: Int) -> [ClipboardHistoryEntry] {
        let cutoff = now.addingTimeInterval(-Double(max(1, retentionDays)) * 86_400)
        var result: [ClipboardHistoryEntry] = []
        var bytes = 0
        var ids = Set<UUID>()
        for entry in entries.sorted(by: { $0.copiedAt > $1.copiedAt }) {
            guard entry.content.isValid, entry.copiedAt > cutoff,
                  ids.insert(entry.id).inserted,
                  !result.contains(where: { $0.content == entry.content }) else { continue }
            guard result.count < maximumEntries, bytes + entry.content.byteCount <= maximumTotalBytes else { continue }
            result.append(entry)
            bytes += entry.content.byteCount
        }
        return result
    }

    static func inserting(_ content: ClipboardHistoryEntry.Content, into entries: [ClipboardHistoryEntry],
                          now: Date, retentionDays: Int) -> [ClipboardHistoryEntry] {
        guard content.isValid else { return entries }
        let id = entries.first(where: { $0.content == content })?.id ?? UUID()
        return trimmed([ClipboardHistoryEntry(id: id, copiedAt: now, content: content)]
                       + entries.filter { $0.content != content }, now: now, retentionDays: retentionDays)
    }
}

actor ClipboardHistoryPersistence {
    private struct Snapshot: Codable {
        let version: Int
        let entries: [ClipboardHistoryEntry]
    }
    private let fileURL: URL
    private var latestRevision = 0

    init(directoryURL: URL) {
        fileURL = directoryURL.appendingPathComponent("clipboard-history.json")
    }

    func load() throws -> [ClipboardHistoryEntry] {
        guard FileManager.default.fileExists(atPath: fileURL.path) else { return [] }
        let size = try fileURL.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0
        guard size <= ClipboardHistoryPolicy.maximumEncodedBytes else { throw CocoaError(.fileReadCorruptFile) }
        let snapshot = try JSONDecoder().decode(Snapshot.self, from: Data(contentsOf: fileURL))
        guard snapshot.version == 1, snapshot.entries.count <= ClipboardHistoryPolicy.maximumEntries else {
            throw CocoaError(.coderReadCorrupt)
        }
        return snapshot.entries
    }

    func save(_ entries: [ClipboardHistoryEntry], revision: Int) throws {
        // Actor calls from different Tasks can arrive out of order. A clear or
        // delete must never be undone by an older queued snapshot.
        guard !Task.isCancelled, revision > latestRevision else { return }
        latestRevision = revision
        let manager = FileManager.default
        if entries.isEmpty {
            if manager.fileExists(atPath: fileURL.path) { try manager.removeItem(at: fileURL) }
            return
        }
        try manager.createDirectory(at: fileURL.deletingLastPathComponent(), withIntermediateDirectories: true,
                                    attributes: [.posixPermissions: 0o700])
        let data = try JSONEncoder().encode(Snapshot(version: 1, entries: entries))
        try data.write(to: fileURL, options: .atomic)
        try manager.setAttributes([.posixPermissions: 0o600], ofItemAtPath: fileURL.path)
    }
}
